#!/bin/bash
FILE=$1

if [ -e "$FILE" ]; then
    read -p "Enter commit message: " text
    if [ "$text" == '' ]; then
        echo "No commit message provided."
    else
        git add "$FILE"
        git commit -m "$text"
        git push
    fi
else
    echo "No arguments entered."
    echo "Syntax: ./gitauto {filename}"
    echo "Example usage: ./gitauto README.md"
fi

